apiVersion: v1
kind: ConfigMap
metadata:
  name: tailhook-webhook-configmap
  namespace: {{ .Values.namespace }}
data:
  sidecarconfig.yaml: |

    {{- if .Values.containers -}}
    {{- range $key, $val := .Values.containers  }}
    {{ $key }}: 
    {{ $val }}
    {{ else }}
    containers:
    - name: sidecar-nginx
      image: nginx:1.12.2
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
    {{- end -}}

    {{- if .Values.containers -}}
    {{- range $key, $val := .Values.volumes  }}
    {{ $key }}: 
    {{ $val }}
    {{ else }}
    volumes:
    - name: nginx-conf
      configMap:
        name: nginx-configmap
    {{- end -}}
