apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailhook-webhook-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: tailhook
spec:
  replicas: {{ .Values.hook_svc_replica_count }}
  selector:
    matchLabels:
      app: tailhook
  template:
    metadata:
      labels:
        app: tailhook
    spec:
      containers:
        - name: tailhook
          image: 4lane-legit/tailhook:latest
          imagePullPolicy: IfNotPresent
          args:
          - -sidecarCfgFile=/etc/webhook/config/sidecarconfig.yaml
          - -tlsCertFile=/etc/webhook/certs/cert.pem
          - -tlsKeyFile=/etc/webhook/certs/key.pem
          - -alsologtostderr
          - -v=4
          - 2>&1
          volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
          - name: webhook-config
            mountPath: /etc/webhook/config
      volumes:
      - name: webhook-certs
        secret:
          secretName: tailhook-webhook-certs
      - name: webhook-config
        configMap:
          name: tailhook-webhook-configmap
