apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: tailhook-webhook-cfg
  labels:
    app: tailhook
webhooks:
- name: tailhook.4lane.legit
  clientConfig:
    service:
      name: tailhook-webhook-svc
      namespace: {{ .Values.namespace }}
      path: "/mutate"
    caBundle: ${CA_BUNDLE}
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
    matchLabels:
      sidecar-injection: enabled
