apiVersion: v1
kind: Service
metadata:
  name: tailhook-webhook-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: tailhook
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: tailhook
