apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-conf
  namespace: {{ .Values.namespace }}
data:
{{ $currentScope := ./confs}}
{{ range $path, $_ :=  .Files.Glob  "**.yaml" }}
    {{- with $currentScope}}
        {{ .Files.Get $path }}
    {{- end }}
{{ end }}
